uat:
  debtor_service_provider:
    client_id: <DEBTOR_SERVICE_PROVIDER_CLIENT_ID>
    service_provider_id: <DEBTOR_SERVICE_PROVIDER_ID>
    client_secret: <DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET>
  creditor_service_provider:
    client_id: <CREDITOR_SERVICE_PROVIDER_CLIENT_ID>
    service_provider_id: <CREDITOR_SERVICE_PROVIDER_ID>
    client_secret: <CREDITOR_SERVICE_PROVIDER_CLIENT_SECRET>
  webpage:
    username: <USERNAME>
    password: <PASSWORD>
