uat:
  debtor_service_provider:
    client_id: <DEBTOR_SERVICE_PROVIDER_CLIENT_ID>
    service_provider_id: <DEBTOR_SERVICE_PROVIDER_ID>
    client_secret: <DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET>
  debtor_service_provider_B:
    client_id: <DEBTOR_SERVICE_PROVIDER_B_CLIENT_ID>
    service_provider_id: <DEBTOR_SERVICE_PROVIDER_B_ID>
    client_secret: <DEBTOR_SERVICE_PROVIDER_B_CLIENT_SECRET>
  creditor_service_provider:
    client_id: <CREDITOR_SERVICE_PROVIDER_CLIENT_ID>
    service_provider_id: <CREDITOR_SERVICE_PROVIDER_ID>
    client_secret: <CREDITOR_SERVICE_PROVIDER_CLIENT_SECRET>
  pagopa_integration_payee_registry:
    client_id: <PAGOPA_INTEGRATION_CLIENT_ID>
    client_secret: <PAGOPA_INTEGRATION_CLIENT_SECRET>
  pagopa_integration_service_registry:
    client_id: <PAGOPA_INTEGRATION_CLIENT_ID>
    client_secret: <PAGOPA_INTEGRATION_CLIENT_SECRET>
  webpage:
    username: <USERNAME>
    password: <PASSWORD>
  CBI_client_id: <CBI_CLIENT_ID>
  CBI_client_secret: <CBI_CLIENT_SECRET>
  CBI_client_PFX_base64: <CBI_CLIENT_PFX_BASE64>
  CBI_client_PFX_password_base64: <CBI_CLIENT_PFX_PASSWORD_BASE64>
  debtor_service_provider_mock_PFX_base64: <DEBTOR_SERVICE_PROVIDER_MOCK_PFX_BASE64>
  debtor_service_provider_mock_PFX_password_base64: <DEBTOR_SERVICE_PROVIDER_MOCK_PFX_PASSWORD_BASE64>
  cbi_activated_fiscal_code: <CBI_ACTIVATED_FISCAL_CODE>
  poste_activated_fiscal_code: <POSTE_ACTIVATED_FISCAL_CODE>
  hype_activated_fiscal_code: <HYPE_ACTIVATED_FISCAL_CODE>
