debtor_service_provider:
  client_id: "@env DEBTOR_SERVICE_PROVIDER_CLIENT_ID"
  service_provider_id: "@env DEBTOR_SERVICE_PROVIDER_ID"
  client_secret: "@env DEBTOR_SERVICE_PROVIDER_CLIENT_SECRET"

debtor_service_provider_B:
  client_id: "@env DEBTOR_SERVICE_PROVIDER_B_CLIENT_ID"
  service_provider_id: "@env DEBTOR_SERVICE_PROVIDER_B_ID"
  client_secret: "@env DEBTOR_SERVICE_PROVIDER_B_CLIENT_SECRET"

creditor_service_provider:
  client_id: "@env CREDITOR_SERVICE_PROVIDER_CLIENT_ID"
  service_provider_id: "@env CREDITOR_SERVICE_PROVIDER_ID"
  client_secret: "@env CREDITOR_SERVICE_PROVIDER_CLIENT_SECRET"

pagopa_integration_payee_registry:
  client_id: "@env PAGOPA_INTEGRATION_PAYEE_REGISTRY_CLIENT_ID"
  client_secret: "@env PAGOPA_INTEGRATION_PAYEE_REGISTRY_CLIENT_SECRET"

pagopa_integration_service_registry:
  client_id: "@env PAGOPA_INTEGRATION_SERVICE_REGISTRY_CLIENT_ID"
  client_secret: "@env PAGOPA_INTEGRATION_SERVICE_REGISTRY_CLIENT_SECRET"

webpage:
  username: "@env WEBPAGE_USERNAME"
  password: "@env WEBPAGE_PASSWORD"

CBI_client_id: "@env CBI_CLIENT_ID"
CBI_client_secret: "@env CBI_CLIENT_SECRET"
CBI_client_PFX_base64: "@env CBI_CLIENT_PFX_BASE64"
CBI_client_PFX_password_base64: "@env CBI_CLIENT_PFX_PASSWORD_BASE64"
debtor_service_provider_mock_PFX_base64: "@env DEBTOR_SERVICE_PROVIDER_MOCK_PFX_BASE64"
debtor_service_provider_mock_PFX_password_base64: "@env DEBTOR_SERVICE_PROVIDER_MOCK_PFX_PASSWORD_BASE64"
cbi_activated_fiscal_code: "@env CBI_ACTIVATED_FISCAL_CODE"
cbi_payee_id: "@env CBI_PAYEE_ID"
poste_activated_fiscal_code: "@env POSTE_ACTIVATED_FISCAL_CODE"
iccrea_activated_fiscal_code: "@env ICCREA_ACTIVATED_FISCAL_CODE"
