apiVersion: apps/v1
kind: Deployment
metadata:
  name: srtp-itn-u-gpd
  namespace: srtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srtp-itn-u-gpd
  template:
    metadata:
      labels:
        app: srtp-itn-u-gpd
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: srtp-itn-workload-identity
      containers:
        - name: gpd-producer
          image: ghcr.io/pagopa/gpd-test:latest
          ports:
            - containerPort: 8000
          env:
            - name: KEYVAULT_NAME
              value: cstar-u-itn-srtp-kv
            - name: EVENTHUB_SECRET_NAME
              value: gdp-eventhub-connection-string
            - name: EVENTHUB_NAMESPACE
              value: pagopa-u-itn-gps-rtp-integration-evh
            - name: EVENTHUB_TOPIC
              value: rtp-events