apiVersion: apps/v1
kind: Deployment
metadata:
  name: srtp-itn-d-gpd
  namespace: srtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srtp-itn-d-gpd
  template:
    metadata:
      labels:
        app: srtp-itn-d-gpd
    spec:
      serviceAccountName: srtp-itn-workload-identity
      containers:
        - name: gpd-producer
          image: ghcr.io/__OWNER__/gpd-test:latest
          ports:
            - containerPort: 8000
          env:
            - name: KEYVAULT_NAME
              value: cstar-d-itn-srtp-kv
            - name: EVENTHUB_SECRET_NAME
              value: gdp-eventhub-connection-string
            - name: EVENTHUB_NAMESPACE
              value: pagopa-d-itn-gps-rtp-integration-evh
            - name: EVENTHUB_TOPIC
              value: rtp-events