from config.configuration import secrets

DEBTOR_SERVICE_PROVIDER_ID = secrets.debtor_service_provider.service_provider_id
DEBTOR_SERVICE_PROVIDER_B_ID = secrets.debtor_service_provider_B.service_provider_id
CBI_PAYEE_ID = secrets.cbi_payee_id
CREDITOR_AGENT_ID = secrets.creditor_agent_id
DEBT_POSITIONS_ORGANIZATION_ID = secrets.debt_positions.organization_id
