name: Build Allure report
description: Install Allure CLI and generate report with history reuse
inputs:
  subfolder:
    description: Subfolder under gh-pages where the report lives
    required: false
    default: aggregate
  allure_version:
    description: Allure CLI version to install
    required: false
    default: '2.32.0'
  gh_pages_path:
    description: Local path of gh-pages checkout
    required: false
    default: gh-pages
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@f4f1212c880fdec8162ea9a6493f4495191887b4 # v4.7.1
      with:
        distribution: temurin
        java-version: '17'
    - name: Install Allure and build report
      shell: bash
      run: |
        set -e
        ALLURE_VERSION="${{ inputs.allure_version }}"
        SUBFOLDER="${{ inputs.subfolder }}"
        GH_PAGES_PATH="${{ inputs.gh_pages_path }}"

        sudo apt-get update
        sudo apt-get install -y unzip curl
        curl -sSL -o "allure-${ALLURE_VERSION}.zip" "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip"
        sudo unzip -o "allure-${ALLURE_VERSION}.zip" -d /usr/local/
        sudo ln -sfn "/usr/local/allure-${ALLURE_VERSION}/bin/allure" /usr/local/bin/allure

        mkdir -p allure-results
        if [ -d "${GH_PAGES_PATH}/${SUBFOLDER}/history" ]; then
          mkdir -p allure-results/history
          cp -r "${GH_PAGES_PATH}/${SUBFOLDER}/history" "allure-results/"
        fi

        allure --version
        if [ ! -d "allure-results" ] || [ -z "$(ls -A allure-results 2>/dev/null)" ]; then
          echo "No allure-results found for subfolder '${SUBFOLDER}'. Skipping report generation."
          mkdir -p "allure-history/${SUBFOLDER}"
          exit 0
        fi

        allure generate "allure-results" --clean -o "allure-report"

        rm -rf "allure-history/${SUBFOLDER}"
        mkdir -p "allure-history/${SUBFOLDER}"
        cp -r allure-report/* "allure-history/${SUBFOLDER}/"
