name: Build & Deploy GPD Test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: itn-dev
        type: choice
        options:
          - itn-dev
          - itn-uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'itn-dev' }}

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: gpd-test/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gpd-test:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@89d153571fe9a34ed70fcf9f1d95ab8debea7a73
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AZURE_AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f gpd-test/deploy/deploy-${{ github.event.inputs.environment || 'itn-dev' }}.yaml

      - name: Restart deployment to pull latest image
        run: |
          kubectl rollout restart deployment rtp-platform-qa -n srtp